name: fast_location
description: FastLocation - Consulta de CEP e Endereços (FastDelivery)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  dio: ^4.0.6

  # State management
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4

  # Local storage
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.2
  path_provider_android: ^2.0.14
  path_provider_ios: ^2.0.9

  # Mapas e geocodificação
  map_launcher: ^2.2.1+1
  geocoding: ^2.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  mobx_codegen: ^2.0.1+3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true